# Generated by Django 4.1.7 on 2023-03-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование разработчика')),
                ('slug', models.SlugField(verbose_name='Developer slug')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('slug', models.SlugField(verbose_name='Genre slug')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Навание игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('language', models.CharField(choices=[(1, 'English'), (2, 'Russian'), (3, 'Ukrainian')], default=3, max_length=255, verbose_name='Языки')),
                ('platform', models.CharField(max_length=255, verbose_name='Платформа')),
                ('type', models.CharField(default='RePack', max_length=255, verbose_name='Тип')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.developer')),
                ('genres', models.ManyToManyField(to='game.genre')),
            ],
        ),
    ]
